.PHONY: default tidy swag build run clean {{ if .Form.DatabaseFlag }}migrate-up migrate-down migrate-status migrate-create{{ end }}

default: run

define check_tool
    @if !command -v $(1) > /dev/null 2>&1; then \
        echo "$(2) is not installed. Please install $(2) to proceed."; \
        exit 1; \
    else \
    	echo "$(2) is already installed."; \
	fi
endef

define install_tool
	@if command -v $(1) > /dev/null 2>&1; then \
		echo "$(2) already installed."; \
	else \
		echo "Installing $(2)..."; \
		go install $(3); \
	fi
endef

install:
	@echo "Installing required Go dependencies to run application..."
	$(call check_tool,go,Go)
	go mod tidy
	@echo "Installing required tools for development..."
{{ if eq .Form.ServerTypeFlag "rest" }}
	$(call install_tool,swag,Swag,github.com/swaggo/swag/cmd/swag@latest)
{{ else if eq .Form.ServerTypeFlag "grpc" }}
	$(call check_tool,protoc,Protocol Buffers Compiler)
	$(call install_tool,protoc-gen-go,protoc-gen-go,google.golang.org/protobuf/cmd/protoc-gen-go@latest)
	$(call install_tool,protoc-gen-go-grpc,protoc-gen-go-grpc,google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest){{ end }}{{ if .Form.DatabaseFlag }}
	$(call install_tool,goose,Goose,github.com/pressly/goose/v3/cmd/goose@latest)
	$(call install_tool,sqlc,SQLC,github.com/sqlc-dev/sqlc/cmd/sqlc@latest){{ end }}
{{ if eq .Form.ServerTypeFlag "rest" }}
generate-api:
	swag init -g ./cmd/server/main.go
{{ else if eq .Form.ServerTypeFlag "grpc" }}
generate-api:
	protoc --go_out=. --go_opt=paths=source_relative \
	    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	    internal/pb/user/user.proto
{{ end }}
build: generate-api {{ if .Form.DatabaseFlag }}generate-db{{ end }}
	go build -o ./bin/main ./cmd/server/main.go

run: install build
	./bin/main

clean:
	rm -rf ./bin
{{ if .Form.DatabaseFlag }}
migrate-up:
	export $$(cat .env | xargs) && goose -dir internal/db/migrations up

migrate-down:
	export $$(cat .env | xargs) && goose -dir internal/db/migrations down

migrate-status:
	export $$(cat .env | xargs) && goose -dir internal/db/migrations status

migrate-create:
	goose -dir internal/db/migrations create $(name) sql

generate-db:
	export $$(cat .env | xargs) && sqlc generate
{{ end }}
{{ if .Form.DockerFlag }}
docker-build:
	docker compose -p {{ .Form.Name }} --env-file .env build --pull --no-cache

docker-run:
	docker compose -p {{ .Form.Name }} --env-file .env up -d

docker-clean:
	docker compose -p {{ .Form.Name }} --env-file .env down --rmi all --volumes --remove-orphans
{{ end }}
