.PHONY: default tidy swag build run clean {{ if .Form.DatabaseFlag }}migrate-up migrate-down migrate-status migrate-create{{ end }}

default: run

tidy:
	go mod tidy
{{ if eq .Form.ServerTypeFlag "rest" }}
generate-api:
	swag init -g ./cmd/server/main.go
{{ else if eq .Form.ServerTypeFlag "grpc" }}
generate-api:
	protoc --go_out=. --go_opt=paths=source_relative \
	    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	    internal/pb/user/user.proto
{{ end }}
build: tidy generate-api {{ if .Form.DatabaseFlag }}generate-db{{ end }}
	go build -o ./bin/main ./cmd/server/main.go

run: build
	./bin/main

clean:
	rm -rf ./bin
{{ if .Form.DatabaseFlag }}
migrate-up:
	export $$(cat .env | xargs) && goose -dir internal/db/migrations up

migrate-down:
	export $$(cat .env | xargs) && goose -dir internal/db/migrations down

migrate-status:
	export $$(cat .env | xargs) && goose -dir internal/db/migrations status

migrate-create:
	goose -dir internal/db/migrations create $(name) sql

generate-db:
	export $$(cat .env | xargs) && sqlc generate
{{ end }}
{{ if .Form.DockerFlag }}
docker-build:
	docker compose -p {{ .Form.Name }} --env-file .env build --pull --no-cache

docker-run:
	docker compose -p {{ .Form.Name }} --env-file .env up -d

docker-clean:
	docker compose -p {{ .Form.Name }} --env-file .env down --rmi all --volumes --remove-orphans
{{ end }}
