.PHONY: default tidy swag build run clean

default: run

tidy:
	go mod tidy

swag:
	swag init -g ./cmd/server/main.go

build: tidy swag
	go build -o ./bin/main ./cmd/server/main.go

run: build
	./bin/main

clean:
	rm -rf ./bin